name: Gradle Precommit
on: [pull_request]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: 14
          distribution: adopt
      - name: Run Gradle
        run: |
          ./gradlew precommit --parallel
